In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
from econml.dml import LinearDML
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier

# ==========================================
# 1. 读取数据
# ==========================================
#df = pd.read_excel('mediate.xlsx')

In [65]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
2023年,4374.0,1.282624e+06,1.094258e+07,-164.0000,273.253025,8885.33395,70594.75,3.719679e+08
2022年,4374.0,1.280809e+06,1.094255e+07,-6.4000,261.752900,8828.00000,69129.25,3.719679e+08
2021年,4374.0,1.279871e+06,1.094256e+07,-2.1000,250.475775,8636.24970,66011.25,3.719679e+08
2020年,4374.0,1.278121e+06,1.094260e+07,-20.6300,242.442463,8602.00000,63535.50,3.719679e+08
2019年,4374.0,1.278343e+06,1.094277e+07,-3.6000,237.177050,8461.00000,60666.25,3.719679e+08
2018年,4374.0,1.276944e+06,1.094285e+07,0.0001,231.593750,8505.00000,58149.00,3.719679e+08
2017年,4374.0,1.274855e+06,1.094280e+07,-3.8000,229.526350,8450.50000,56091.75,3.719679e+08
2016年,4374.0,1.273645e+06,1.094290e+07,-12.3000,217.061050,8461.00000,53273.75,3.719679e+08
2015年,4374.0,1.271609e+06,1.094288e+07,-6.4000,224.710350,8510.06640,50633.00,3.719679e+08
2014年,4374.0,1.270574e+06,1.094286e+07,-11.5000,228.558225,8606.50000,49456.00,3.719679e+08
2013年,4374.0,1.269224e+06,1.094281e+07,-19.3800,230.190975,8448.50000,46958.25,3.719679e+08
2012年,4374.0,1.259750e+06,1.094270e+07,-0.7000,226.551550,7949.50000,43606.75,3.719679e+08
2011年,4374.0,3.252382e+06,1.022972e+08,0.0001,218.333475,7515.50000,39516.50,6.253089e+09
2010年,4374.0,1.109760e+06,9.887449e+06,0.0001,199.696175,6709.50000,35952.25,3.415417e+08
2009年,4374.0,9.121161e+05,8.335514e+06,-1.2000,163.791325,5794.00000,31352.75,2.968410e+08
2008年,4374.0,6.921712e+05,6.417164e+06,0.0001,174.277000,5739.50000,30135.00,2.416612e+08
2007年,4374.0,6.067897e+05,5.615751e+06,0.0001,162.008625,5097.50000,27987.25,2.170995e+08

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4375 entries, 0 to 4374
Data columns (total 19 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   指标名称(单位)  4375 non-null   object
 1   地区        4375 non-null   object
 2   2023年     4374 non-null   float64
 3   2022年     4374 non-null   float64
 4   2021年     4374 non-null   float64
 5   2020年     4374 non-null   float64
 6   2019年     4374 non-null   float64
 7   2018年     4374 non-null   float64
 8   2017年     4374 non-null   float64
 9   2016年     4374 non-null   float64
 10  2015年     4374 non-null   float64
 11  2014年     4374 non-null   float64
 12  2013年     4374 non-null   float64
 13  2012年     4374 non-null   float64
 14  2011年     4374 non-null   float64
 15  2010年     4374 non-null   float64
 16  2009年     4374 non-null   float64
 17  2008年     4374 non-null   float64
 18  2007年     4374 non-null   float64
dtypes: float64(17), object(2)
memory usage: 649.5+ KB

In [67]:
df.head(10)

,指标名称(单位),地区,2023年,2022年,2021年,2020年,2019年,2018年,2017年,2016年,2015年,2014年,2013年,2012年,2011年,2010年,2009年,2008年,2007年
0,GDP(亿元),北京市,43761.0,41611.0,40270.0,36103.0,35371.0,30319.9800,27994.55500,25669.1300,23014.5900,21330.8300,19500.5600,17879.4000,16251.9300,14113.5800,12153.0000,10488.0500,9353.3200
1,GDP(亿元),天津市,16737.0,16311.0,15695.0,14084.0,14104.0,18809.6400,18347.51500,17885.3900,16538.1900,15726.9300,14370.1600,12893.8800,11307.2800,9224.4600,7521.8500,6354.3800,5050.4000
2,GDP(亿元),石家庄市,7534.0,7101.0,6490.0,5935.0,5810.0,6082.6180,6005.17365,5927.7293,5440.5988,5170.2653,4863.6583,4500.2098,4082.6833,3401.0186,3001.2797,2838.3712,2360.7230
3,GDP(亿元),唐山市,9133.0,8901.0,8231.0,7211.0,6890.0,6954.9700,6654.91875,6354.8675,6103.0601,6225.3023,6121.2139,5861.6363,5442.4541,4469.1588,3812.7192,3561.1900,2779.4190
4,GDP(亿元),秦皇岛市,2001.0,1910.0,1844.0,1686.0,1612.0,1635.5631,1492.45785,1349.3526,1250.4439,1200.0219,1168.7549,1139.3664,1070.0808,930.4969,804.5421,808.9526,683.5782
5,GDP(亿元),邯郸市,4382.0,4346.0,4115.0,3637.0,3486.0,3454.5705,3395.83040,3337.0903,3145.4319,3080.0054,3061.5043,3024.2864,2789.0278,2361.5569,2015.2800,1990.3633,1608.1303
6,GDP(亿元),邢台市,2586.0,2547.0,2427.0,2200.0,2120.0,2150.7611,2063.25355,1975.7460,1764.7323,1646.9408,1604.5756,1532.0620,1428.9231,1212.0943,1056.2913,989.0039,890.7487
7,GDP(亿元),保定市,4825.0,4608.0,4402.0,3954.0,3772.0,3589.7885,3533.45770,3477.1269,3000.3400,3035.2036,2904.3115,2720.9000,2449.9000,2050.3000,1730.0023,1580.8884,1375.1799
8,GDP(亿元),张家口市,1843.0,1775.0,1728.0,1600.0,1551.0,1536.6202,1501.30565,1465.9911,1363.5443,1348.9726,1316.9971,1233.5529,1118.6100,966.4158,800.3407,720.3705,566.3192
9,GDP(亿元),承德市,1852.0,1780.0,1697.0,1550.0,1471.0,1481.5102,1460.04215,1438.5741,1358.7278,1342.5500,1272.0917,1181.9213,1104.2013,888.9619,760.1136,714.9413,553.5406

In [ ]:
df_long = df.melt(id_vars=['指标名称(单位)', '地区'], 
                  var_name='年份', 
                  value_name='数值')

df_long['年份'] = df_long['年份'].astype(str).str.extract('(\d+)').astype(int)

df_final = df_long.pivot_table(index=['地区', '年份'], 
                               columns='指标名称(单位)', 
                               values='数值').reset_index()
#df_final.to_execl()

指标名称(单位)    地区    年份   GDP(亿元)  GDP增长率(%)  人均GDP(元)  供水量(市辖区)(万吨)  公共财政支出(万元)  \
0         七台河市  2007  135.1595       14.9   15137.0       10000.0         NaN
1         七台河市  2008  187.1613       25.6   20826.0        8545.0         NaN
2         七台河市  2009  233.6262       26.0   25534.0        5349.0         NaN
3         七台河市  2010  305.2237       25.1   32890.0        3128.0         NaN
4         七台河市  2011  302.0659       16.7   32599.0        3786.0         NaN

指标名称(单位)  公共财政收入(万元)  医院床位数(张)  单位从业人员数(人)  地方一般公共预算支出中科学技术支出(万元)  \
0                NaN    3959.0    159300.0                  925.0
1                NaN    3959.0    138700.0                 1284.0
2                NaN    3959.0    132300.0                 1244.0
3                NaN    3959.0    134300.0                 1110.0
4                NaN    3959.0    140700.0                 1832.0

指标名称(单位)  外商直接投资额(万美元)  天然气供气总量(市辖区)(万立方米)  工业用电量(亿千瓦时)  普通高等学校在校学生数(人)  \
0                128.0              1045.0      16.9819          2600.0
1                197.0              1045.0      16.9819          2479.0
2                407.0              1045.0      16.9819          2424.0
3               1390.0              1045.0      16.9819          1789.0
4               1337.0              1045.0      16.9819          1463.0

指标名称(单位)  货物出口额(亿美元)  货物进口额(亿美元)  金融机构各项贷款余额(万元)  金融机构存款余额(亿元)
0             0.0429      0.0129       1019088.0      140.3828
1             0.0429      0.0129        913444.0      182.5584
2             0.0429      0.0129       1264415.0      221.4596
3             0.0429      0.0129       1640313.0      257.7580
4             0.0429      0.0129       1783841.0      295.2569

In [75]:
df_final = pd.read_excel('final.xlsx')
df_final['地区'] = df_final['地区'].apply(lambda x: x.rstrip('市'))

In [76]:
df_final

,Unnamed: 0,地区,年份,GDP(亿元),GDP增长率(%),人均GDP(元),供水量(市辖区)(万吨),医院床位数(张),单位从业人员数(人),地方一般公共预算支出中科学技术支出(万元),外商直接投资额(万美元),天然气供气总量(市辖区)(万立方米),工业用电量(亿千瓦时),普通高等学校在校学生数(人),货物出口额(亿美元),货物进口额(亿美元),金融机构各项贷款余额(万元),金融机构存款余额(亿元)
0,0,七台河,2007,135.1595,14.90,15137.0,10000.0,3959.0,159300.0,925.0,128.0,1045.0,16.981900,2600.0,0.0429,0.0129,1019088.0,140.3828
1,1,七台河,2008,187.1613,25.60,20826.0,8545.0,3959.0,138700.0,1284.0,197.0,1045.0,16.981900,2479.0,0.0429,0.0129,913444.0,182.5584
2,2,七台河,2009,233.6262,26.00,25534.0,5349.0,3959.0,132300.0,1244.0,407.0,1045.0,16.981900,2424.0,0.0429,0.0129,1264415.0,221.4596
3,3,七台河,2010,305.2237,25.10,32890.0,3128.0,3959.0,134300.0,1110.0,1390.0,1045.0,16.981900,1789.0,0.0429,0.0129,1640313.0,257.7580
4,4,七台河,2011,302.0659,16.70,32599.0,3786.0,3959.0,140700.0,1832.0,1337.0,1045.0,16.981900,1463.0,0.0429,0.0129,1783841.0,295.2569
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5061,5061,龙岩,2019,2679.0000,7.10,101476.0,8701.0,17582.0,303530.0,133880.0,4781.0,9312.0,88.713600,18044.0,23.3167,14.8406,8745487.0,908.4257
5062,5062,龙岩,2020,2871.0000,5.31,105548.0,8701.0,18771.0,303530.0,88180.0,4781.0,9312.0,89.746375,18044.0,23.3167,14.8406,8745487.0,908.4257
5063,5063,龙岩,2021,3082.0000,7.70,112886.0,8701.0,19225.0,303530.0,136333.0,4781.0,9312.0,90.779150,18044.0,23.3167,14.8406,8745487.0,908.4257
5064,5064,龙岩,2022,3314.0000,4.97,121721.0,8701.0,14992.0,303530.0,138310.0,4781.0,9312.0,91.811925,18044.0,23.3167,14.8406,8745487.0,908.4257
5065,5065,龙岩,2023,3318.0000,3.77,122683.0,8701.0,15181.0,303530.0,93238.0,4781.0,8401.0,92.844700,18044.0,23.3167,14.8406,8745487.0,908.4257

In [2]:
df1 = pd.read_excel('1_插值补充后数据.xlsx')
df = pd.merge(df1, df_final, 
                    left_on=['地级市', '年份_final'], 
                    right_on=['地区', '年份'], 
                    how='left')
# 方法1：直接删
df.drop(['年份_db', '省份_db', '城市', '省份代码_db', '城市代码', '地区', '年份','Unnamed: 0'], axis=1, inplace=True)
#df.to_excel('mediate_merge.xlsx')

NameError: name 'df_final' is not defined

In [85]:
#构建评分环节
weights = {
    'GDP(亿元)': 0.1601,
    'GDP增长率(%)': 0.0883,
    '人均GDP(元)': 0.0516,
    '供水量(市辖区)(万吨)': 0.0249,
    '医院床位数(张)': 0.0267,
    '单位从业人员数(人)': 0.1165,
    '地方一般公共预算支出中科学技术支出(万元)': 0.1348,
    '外商直接投资额(万美元)': 0.0465,
    '天然气供气总量(市辖区)(万立方米)': 0.0249,
    '工业用电量(亿千瓦时)': 0.0494,
    '普通高等学校在校学生数(人)_y': 0.1005,
    '货物出口额(亿美元)': 0.0381,
    '货物进口额(亿美元)': 0.0381,
    '金融机构各项贷款余额(万元)': 0.0498,
    '金融机构存款余额(亿元)': 0.0498
}
cols = list(weights.keys())
#采用映射到0-1的min_max函数:
def min_max_norm(x):
    if x.max() == x.min():
        return pd.Series(0.5, index=x.index)
    return (x - x.min()) / (x.max() - x.min())

In [ ]:
df_norm = df.groupby('年份_final')[cols].transform(min_max_norm)
df['营商环境得分'] = df_norm.apply(lambda row: sum(row[col] * weights[col] for col in cols), axis=1)
df['营商环境得分'] = df['营商环境得分'] * 100

In [94]:
df=df.dropna(subset=['营商环境得分'],axis = 0)
df.to_excel('mediate_merge_final.xlsx')

In [3]:
df = pd.read_excel('mediate_merge_final.xlsx')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4692 entries, 0 to 4691
Data columns (total 48 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             4692 non-null   int64
 1   省份_final               4692 non-null   object
 2   省份代码_final             4692 non-null   int64
 3   地级市                    4692 non-null   object
 4   地级市代码                  4692 non-null   int64
 5   年份_final               4692 non-null   int64
 6   初次开放数据平台年份             3298 non-null   float64
 7   treat（是否开放数据平台虚拟变量）    4692 non-null   int64
 8   post（开放数据平台时间虚拟变量）     4692 non-null   int64
 9   DID                    4692 non-null   int64
 10  诉求量                    4692 non-null   int64
 11  所属地域                   4692 non-null   object
 12  胡焕庸线                   4692 non-null   object
 13  地区生产总值(万元)             4692 non-null   float64
 14  人均地区生产总值(元)            4692 non-null   float64
 15  第三产业增加值占GDP比重(%)       4692 non-null   float64
 16  户籍人口(万人)               4692 non-null   float64
 17  行政区域土地面积(平方公里)         4692 non-null   float64
 18  人口密度(人／平方公里)           4692 non-null   float64
 19  地方财政一般预算内支出(万元)        4692 non-null   int64
 20  地方财政一般预算内收入(万元)        4692 non-null   int64
 21  科学支出(万元)               4692 non-null   int64
 22  年末金融机构各项贷款余额(万元)       4692 non-null   int64
 23  普通高等学校在校学生数(人)_x       4692 non-null   float64
 24  公共图书馆图书总藏量(千册、件)       4692 non-null   float64
 25  每百人公共图书馆藏书(册、件)        4692 non-null   int64
 26  公路客运量(万人)              4692 non-null   float64
 27  公路货运量(万吨)              4692 non-null   float64
 28  电信业务收入(万元)             4692 non-null   float64
 29  高速公路里程(公里)             4692 non-null   int64
 30  外商投资企业数(个)             4658 non-null   float64
 31  生活垃圾无害化处理率(%)          4692 non-null   float64
 32  GDP(亿元)                4692 non-null   float64
 33  GDP增长率(%)              4692 non-null   float64
 34  人均GDP(元)               4692 non-null   float64
 35  供水量(市辖区)(万吨)           4692 non-null   float64
 36  医院床位数(张)               4692 non-null   float64
 37  单位从业人员数(人)             4692 non-null   float64
 38  地方一般公共预算支出中科学技术支出(万元)  4692 non-null   float64
 39  外商直接投资额(万美元)           4692 non-null   float64
 40  天然气供气总量(市辖区)(万立方米)     4692 non-null   int64
 41  工业用电量(亿千瓦时)            4692 non-null   float64
 42  普通高等学校在校学生数(人)_y       4692 non-null   float64
 43  货物出口额(亿美元)             4692 non-null   float64
 44  货物进口额(亿美元)             4692 non-null   float64
 45  金融机构各项贷款余额(万元)         4692 non-null   int64
 46  金融机构存款余额(亿元)           4692 non-null   float64
 47  营商环境得分                 4692 non-null   float64
dtypes: float64(28), int64(16), object(4)
memory usage: 1.7+ MB

In [5]:
column = df.columns.to_list()
column_need = column[13:]
column_need

['地区生产总值(万元)',
 '人均地区生产总值(元)',
 '第三产业增加值占GDP比重(%)',
 '户籍人口(万人)',
 '行政区域土地面积(平方公里)',
 '人口密度(人／平方公里)',
 '地方财政一般预算内支出(万元)',
 '地方财政一般预算内收入(万元)',
 '科学支出(万元)',
 '年末金融机构各项贷款余额(万元)',
 '普通高等学校在校学生数(人)_x',
 '公共图书馆图书总藏量(千册、件)',
 '每百人公共图书馆藏书(册、件)',
 '公路客运量(万人)',
 '公路货运量(万吨)',
 '电信业务收入(万元)',
 '高速公路里程(公里)',
 '外商投资企业数(个)',
 '生活垃圾无害化处理率(%)',
 'GDP(亿元)',
 'GDP增长率(%)',
 '人均GDP(元)',
 '供水量(市辖区)(万吨)',
 '医院床位数(张)',
 '单位从业人员数(人)',
 '地方一般公共预算支出中科学技术支出(万元)',
 '外商直接投资额(万美元)',
 '天然气供气总量(市辖区)(万立方米)',
 '工业用电量(亿千瓦时)',
 '普通高等学校在校学生数(人)_y',
 '货物出口额(亿美元)',
 '货物进口额(亿美元)',
 '金融机构各项贷款余额(万元)',
 '金融机构存款余额(亿元)',
 '营商环境得分']

In [6]:
df_clean = df.dropna(subset = column_need)
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4658 entries, 0 to 4691
Data columns (total 48 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             4658 non-null   int64
 1   省份_final               4658 non-null   object
 2   省份代码_final             4658 non-null   int64
 3   地级市                    4658 non-null   object
 4   地级市代码                  4658 non-null   int64
 5   年份_final               4658 non-null   int64
 6   初次开放数据平台年份             3264 non-null   float64
 7   treat（是否开放数据平台虚拟变量）    4658 non-null   int64
 8   post（开放数据平台时间虚拟变量）     4658 non-null   int64
 9   DID                    4658 non-null   int64
 10  诉求量                    4658 non-null   int64
 11  所属地域                   4658 non-null   object
 12  胡焕庸线                   4658 non-null   object
 13  地区生产总值(万元)             4658 non-null   float64
 14  人均地区生产总值(元)            4658 non-null   float64
 15  第三产业增加值占GDP比重(%)       4658 non-null   float64
 16  户籍人口(万人)               4658 non-null   float64
 17  行政区域土地面积(平方公里)         4658 non-null   float64
 18  人口密度(人／平方公里)           4658 non-null   float64
 19  地方财政一般预算内支出(万元)        4658 non-null   int64
 20  地方财政一般预算内收入(万元)        4658 non-null   int64
 21  科学支出(万元)               4658 non-null   int64
 22  年末金融机构各项贷款余额(万元)       4658 non-null   int64
 23  普通高等学校在校学生数(人)_x       4658 non-null   float64
 24  公共图书馆图书总藏量(千册、件)       4658 non-null   float64
 25  每百人公共图书馆藏书(册、件)        4658 non-null   int64
 26  公路客运量(万人)              4658 non-null   float64
 27  公路货运量(万吨)              4658 non-null   float64
 28  电信业务收入(万元)             4658 non-null   float64
 29  高速公路里程(公里)             4658 non-null   int64
 30  外商投资企业数(个)             4658 non-null   float64
 31  生活垃圾无害化处理率(%)          4658 non-null   float64
 32  GDP(亿元)                4658 non-null   float64
 33  GDP增长率(%)              4658 non-null   float64
 34  人均GDP(元)               4658 non-null   float64
 35  供水量(市辖区)(万吨)           4658 non-null   float64
 36  医院床位数(张)               4658 non-null   float64
 37  单位从业人员数(人)             4658 non-null   float64
 38  地方一般公共预算支出中科学技术支出(万元)  4658 non-null   float64
 39  外商直接投资额(万美元)           4658 non-null   float64
 40  天然气供气总量(市辖区)(万立方米)     4658 non-null   int64
 41  工业用电量(亿千瓦时)            4658 non-null   float64
 42  普通高等学校在校学生数(人)_y       4658 non-null   float64
 43  货物出口额(亿美元)             4658 non-null   float64
 44  货物进口额(亿美元)             4658 non-null   float64
 45  金融机构各项贷款余额(万元)         4658 non-null   int64
 46  金融机构存款余额(亿元)           4658 non-null   float64
 47  营商环境得分                 4658 non-null   float64
dtypes: float64(28), int64(16), object(4)
memory usage: 1.7+ MB

In [7]:
df_clean.describe().T

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,4658.0,2.498872e+03,1.495183e+03,0.000000,1.266250e+03,2.430500e+03,3.713750e+03,5.524000e+03
省份代码_final,4658.0,3.732482e+01,1.373142e+01,11.000000,3.200000e+01,3.700000e+01,4.500000e+01,6.500000e+01
地级市代码,4658.0,3.739434e+05,1.373407e+05,110000.000000,3.202000e+05,3.710500e+05,4.505000e+05,6.502000e+05
年份_final,4658.0,2.015000e+03,4.899505e+00,2007.000000,2.011000e+03,2.015000e+03,2.019000e+03,2.023000e+03
初次开放数据平台年份,3264.0,2.019932e+03,2.271223e+00,2012.000000,2.019000e+03,2.020000e+03,2.021000e+03,2.024000e+03
treat（是否开放数据平台虚拟变量）,4658.0,7.007299e-01,4.579875e-01,0.000000,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
post（开放数据平台时间虚拟变量）,4658.0,1.676685e-01,3.736118e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
DID,4658.0,1.676685e-01,3.736118e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
诉求量,4658.0,1.218763e+01,6.650692e+01,0.000000,0.000000e+00,0.000000e+00,2.750000e+00,2.360000e+03
地区生产总值(万元),4658.0,2.595676e+07,3.929931e+07,848176.000000,7.518308e+06,1.381590e+07,2.772716e+07,4.721900e+08
人均地区生产总值(元),4658.0,5.137813e+04,3.531212e+04,3398.000000,2.639875e+04,4.248200e+04,6.582200e+04,2.646990e+05
第三产业增加值占GDP比重(%),4658.0,4.163056e+01,1.031491e+01,8.580000,3.434000e+01,4.097000e+01,4.805000e+01,8.485000e+01
户籍人口(万人),4658.0,4.574018e+02,3.216699e+02,29.970000,2.494250e+02,3.850500e+02,5.927500e+02,3.416000e+03
行政区域土地面积(平方公里),4658.0,1.668832e+04,2.191960e+04,1113.000000,7.656250e+03,1.223600e+04,1.903600e+04,2.615700e+05
人口密度(人／平方公里),4658.0,4.318122e+02,3.294043e+02,5.000000,1.870000e+02,3.580000e+02,6.320000e+02,2.648000e+03
地方财政一般预算内支出(万元),4658.0,4.059363e+06,6.595166e+06,170791.000000,1.433492e+06,2.563735e+06,4.371864e+06,9.638513e+07
地方财政一般预算内收入(万元),4658.0,2.301293e+06,5.379895e+06,32397.000000,4.726760e+05,9.726505e+05,1.942070e+06,8.312501e+07
科学支出(万元),4658.0,1.160066e+05,3.892221e+05,-164.000000,9.638250e+03,2.442200e+04,7.672350e+04,5.549817e+06
年末金融机构各项贷款余额(万元),4658.0,3.599670e+07,8.267894e+07,498012.000000,5.355681e+06,1.146873e+07,2.749881e+07,1.086012e+09
普通高等学校在校学生数(人)_x,4658.0,9.990092e+04,1.758560e+05,231.000000,1.747425e+04,3.834500e+04,8.746925e+04,1.489276e+06
公共图书馆图书总藏量(千册、件),4658.0,3.268467e+03,7.441001e+03,64.000000,7.900000e+02,1.370500e+03,2.729750e+03,1.374900e+05
每百人公共图书馆藏书(册、件),4658.0,5.931301e+01,1.053548e+02,2.000000,2.100000e+01,3.300000e+01,6.200000e+01,4.325000e+03
公路客运量(万人),4658.0,6.653863e+03,1.230687e+04,1.000000,1.607500e+03,3.597000e+03,7.360250e+03,1.955970e+05
公路货运量(万吨),4658.0,1.126433e+04,1.311490e+04,20.000000,4.386250e+03,7.898500e+03,1.419575e+04,2.924260e+05
电信业务收入(万元),4658.0,4.564573e+05,8.211772e+05,23.000000,1.414872e+05,2.398058e+05,4.447578e+05,1.396402e+07
高速公路里程(公里),4658.0,5.042261e+02,3.616749e+02,10.000000,2.850000e+02,4.530000e+02,6.360000e+02,8.262000e+03
外商投资企业数(个),4658.0,1.007685e+02,3.180130e+02,1.000000,7.000000e+00,1.500000e+01,5.200000e+01,4.773000e+03
生活垃圾无害化处理率(%),4658.0,9.060141e+01,1.807031e+01,0.440000,9.048250e+01,9.999000e+01,1.000000e+02,1.000000e+02
GDP(亿元),4658.0,1.345035e+06,9.162093e+07,73.652300,7.525445e+02,1.382202e+03,2.778778e+03,6.253089e+09
GDP增长率(%),4658.0,9.040179e+00,4.887482e+00,-20.630000,6.100000e+00,8.500000e+00,1.250000e+01,1.090000e+02
人均GDP(元),4658.0,5.851190e+05,3.641465e+07,99.000000,2.644650e+04,4.248950e+04,6.582200e+04,2.485333e+09
供水量(市辖区)(万吨),4658.0,1.652488e+04,3.182827e+04,398.000000,3.907750e+03,7.031500e+03,1.471600e+04,3.494810e+05
医院床位数(张),4658.0,2.221071e+04,2.034354e+04,1941.000000,1.082775e+04,1.627450e+04,2.599800e+04,1.898810e+05
单位从业人员数(人),4658.0,5.769537e+05,8.775873e+05,5.970000,2.159240e+05,3.431000e+05,5.636420e+05,9.543400e+06
地方一般公共预算支出中科学技术支出(万元),4658.0,1.159964e+05,3.891088e+05,-164.000000,9.643000e+03,2.442200e+04,7.672350e+04,5.549817e+06
外商直接投资额(万美元),4658.0,8.652030e+04,2.044567e+05,3.000000,5.533875e+03,2.058300e+04,7.416175e+04,3.082563e+06
天然气供气总量(市辖区)(万立方米),4658.0,5.747518e+04,1.686122e+05,77.000000,8.531000e+03,1.879500e+04,4.200400e+04,2.011672e+06
工业用电量(亿千瓦时),4658.0,1.446134e+02,1.580554e+02,2.876700,4.887930e+01,9.106678e+01,1.821630e+02,1.235375e+03
普通高等学校在校学生数(人)_y,4658.0,9.251663e+04,1.635237e+05,231.000000,1.620000e+04,3.483300e+04,8.069075e+04,1.057281e+06
货物出口额(亿美元),4658.0,8.257267e+01,2.760825e+02,0.001100,2.637700e+00,1.079135e+01,3.451070e+01,2.443579e+03
货物进口额(亿美元),4658.0,7.952370e+01,3.341422e+02,0.000600,7.998000e-01,5.039600e+00,2.385000e+01,3.160789e+03
金融机构各项贷款余额(万元),4658.0,1.732947e+07,3.744698e+07,498012.000000,3.204359e+06,5.460673e+06,1.179387e+07,3.719679e+08
金融机构存款余额(亿元),4658.0,2.524367e+03,5.968010e+03,114.888200,5.770172e+02,1.005354e+03,1.844508e+03,6.988387e+04
营商环境得分,4658.0,1.143491e+01,9.192075e+00,0.714622,7.000904e+00,8.986942e+00,1.201466e+01,8.280720e+01

In [8]:
df = df_clean.copy()
# ==========================================
# 3. 构造文献要求的控制变量
# ==========================================
# 注意：等号右侧的 ['列名'] 需要你对照生成的 "1_插值补充后数据.xlsx" 里的实际基础表头进行替换
df['人力资本水平'] = df['普通高等学校在校学生数(人)_x'] / df['户籍人口(万人)']
df['传统基础设施'] = np.log(df['公路货运量(万吨)'] +1 ) # 加1防止出现log(0)
df['互联网发展水平'] = np.log(df['电信业务收入(万元)'] +1)
df['金融发展水平'] = df['年末金融机构各项贷款余额(万元)'] / df['地区生产总值(万元)']
df['财政压力水平'] = df['地方财政一般预算内支出(万元)'] / df['地方财政一般预算内收入(万元)']
df['科学支出水平'] = np.log(df['科学支出(万元)']+165 )
df['城市发展水平'] = np.log(df['人均地区生产总值(元)']+1)
df['外商投资水平'] = np.log(df['外商投资企业数(个)']+1)
df['交通便捷程度'] = df['高速公路里程(公里)'] / df['户籍人口(万人)']
# 将构造好的控制变量放入列表
controls = ['地区生产总值(万元)','人口密度(人／平方公里)', '第三产业增加值占GDP比重(%)', '人力资本水平', '每百人公共图书馆藏书(册、件)',
            '传统基础设施', '互联网发展水平', '金融发展水平', '财政压力水平', '科学支出水平','城市发展水平','外商投资水平','生活垃圾无害化处理率(%)','交通便捷程度']

# 剔除在构造变量后仍然存在缺失值（如缺乏某城市整体面积数据导致无法插值）的样本
df.dropna(subset=['诉求量', 'post（开放数据平台时间虚拟变量）'] + controls, inplace=True)
#df.to_excel("2_处理后含控制变量数据.xlsx", index=False)

In [9]:
# ==========================================
# 4. 双重机器学习 (DML) 基准回归结合中介效应
# ==========================================
df['诉求量_log'] = np.log1p(df['诉求量'])
Y = df['诉求量_log'].values
T = df['post（开放数据平台时间虚拟变量）'].values
X = df[controls].values
M = df['营商环境得分'].values
# 提取城市与年份固定效应，转化为虚拟变量矩阵，作为混杂因素 W
# DML第一阶段会利用机器学习算法剥离W对Y和T的影响，从而获得纯净的因果效应
W_df = pd.get_dummies(df[['地级市', '年份_final']], columns=['地级市', '年份_final'], drop_first=True)
W = W_df.values

In [10]:
from econml.dml import LinearDML
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
# --- 准备工作 ---
# 确保 X 中不包含用来计算 M 的原始指标，避免共线性逻辑错误
# 如果 controls 里有 GDP 等，建议在此处剔除
# ==========================================
# 路径 A: T (政策) -> M (营商环境)
# ==========================================
print("正在拟合路径 A (T -> M)...")
est_a = LinearDML(model_y=RandomForestRegressor(n_estimators=100), 
                  model_t=RandomForestClassifier(n_estimators=100), 
                  discrete_treatment=True, cv=5)
est_a.fit(M, T, X=X, W=W)

# 提取系数（等同于方程3中的 gamma_1）
gamma_1 = est_a.intercept_ 
print(f"路径 A (T->M) 的平均效应系数: {gamma_1:.4f}")
print(est_a.summary().tables[0])

# ==========================================
# 路径 B: M (营商环境) -> Y (诉求量)
# ==========================================
print("\n正在拟合路径 B (M -> Y)...")
# 将 T 加入混杂因素 W，以控制政策本身的直接影响
W_with_T = np.hstack([W, T.reshape(-1, 1)])

est_b = LinearDML(model_y=RandomForestRegressor(n_estimators=100), 
                  model_t=RandomForestRegressor(n_estimators=100), 
                  discrete_treatment=False, # M 是连续得分
                  cv=5)
est_b.fit(Y, M, X=X, W=W_with_T)

# 提取系数（等同于方程2中的 beta_2）
beta_2 = est_b.intercept_
print(f"路径 B (M->Y) 的平均效应系数: {beta_2:.4f}")
print(est_b.summary().tables[0])

正在拟合路径 A (T -> M)...
路径 A (T->M) 的平均效应系数: -16.4196
                    Coefficient Results
===========================================================
    point_estimate stderr  zstat   pvalue ci_lower ci_upper
-----------------------------------------------------------
X0             0.0    0.0    2.296  0.022      0.0      0.0
X1           0.001  0.001    1.207  0.227     -0.0    0.002
X2           0.044  0.018    2.411  0.016    0.008     0.08
X3            -0.0  0.001   -0.075   0.94   -0.002    0.002
X4           0.001  0.003    0.436  0.663   -0.005    0.007
X5          -0.124  0.002  -62.648    0.0   -0.128    -0.12
X6           0.471    0.0  970.049    0.0     0.47    0.472
X7          -0.234  0.002   -96.43    0.0   -0.238   -0.229
X8           0.137  0.004   31.808    0.0    0.129    0.146
X9          -0.076  0.001  -96.497    0.0   -0.077   -0.074
X10          0.674  0.001  646.105    0.0    0.672    0.676
X11         -0.474  0.001 -353.931    0.0   -0.477   -0.472
X12          0.033  0.008    3.868    0.0    0.016    0.049
X13          0.044  0.033    1.351  0.177    -0.02    0.108
-----------------------------------------------------------

正在拟合路径 B (M -> Y)...
路径 B (M->Y) 的平均效应系数: -0.2946
                   Coefficient Results
==========================================================
    point_estimate stderr  zstat  pvalue ci_lower ci_upper
----------------------------------------------------------
X0            -0.0    0.0  -1.594  0.111     -0.0      0.0
X1             0.0    0.0   0.707   0.48     -0.0      0.0
X2           0.001  0.001   1.587  0.113     -0.0    0.002
X3            -0.0    0.0  -2.754  0.006     -0.0     -0.0
X4            -0.0    0.0  -1.366  0.172     -0.0      0.0
X5           0.003  0.001   5.498    0.0    0.002    0.005
X6          -0.003  0.001  -3.702    0.0   -0.004   -0.001
X7            0.01    0.0 315.286    0.0     0.01     0.01
X8            0.01    0.0 271.061    0.0     0.01     0.01
X9           0.004  0.001   6.213    0.0    0.003    0.005
X10          0.022  0.001  37.128    0.0    0.021    0.024
X11         -0.002    0.0  -5.255    0.0   -0.003   -0.001
X12            0.0    0.0   0.138   0.89     -0.0      0.0
X13         -0.008    0.0 -48.986    0.0   -0.009   -0.008
----------------------------------------------------------

In [13]:
# ==========================================
# 路径 A: T (政策) -> M (营商环境)
# ==========================================
print("正在拟合路径 A (T -> M)...")

est_a = LinearDML(
    model_y=RandomForestRegressor(n_estimators=70, random_state=42,max_depth= 10),
    model_t=RandomForestClassifier(n_estimators=70, random_state=42,max_depth= 10),
    discrete_treatment=True,
    cv=5,
    random_state=42
)

est_a.fit(Y=M, T=T, X=X, W=W)

# 获取政策对营商环境的平均处理效应
ate_a = est_a.intercept_
print(f"路径 A (T→M) 的平均效应: {ate_a:.4f}")

# 查看详细结果
print("\n路径A详细结果:")
print(est_a.summary())

# 异质效应
a_effects = est_a.effect(X)
print(f"效应范围: [{a_effects.min():.4f}, {a_effects.max():.4f}]")

# 提取系数和标准误（用于后续中介效应计算）
a_coef = ate_a
#a_se = est_a.summary().tables[0]['std err'][0]  # 提取标准误
#print(f"\n路径A系数提取: a = {a_coef:.4f}, se(a) = {a_se:.4f}")


# ==========================================
# 路径 B: M (营商环境) -> Y (创业活力)
# ==========================================
print("\n正在拟合路径 B (M -> Y)...")

# 将 T 和原始 W 合并作为控制变量（在控制政策直接效应的条件下估计 M→Y）
if W is not None:
    W_for_b = np.column_stack([W, T])
else:
    W_for_b = T.reshape(-1, 1)

est_b = LinearDML(
    model_y=RandomForestRegressor(n_estimators=70, random_state=42,max_depth= 10),
    model_t=RandomForestRegressor(n_estimators=70, random_state=42,max_depth= 10),  # M 是连续变量
    discrete_treatment=False,  # 关键：M 是连续变量
    cv=5,
    random_state=42
)

est_b.fit(Y=Y, T=M, X=X, W=W_for_b)

# 获取营商环境对创业活力的平均效应
ate_b = est_b.intercept_
print(f"路径 B (M→Y) 的平均效应: {ate_b:.4f}")

# 查看详细结果
print("\n路径B详细结果:")
print(est_b.summary())

# 提取系数和标准误
b_coef = ate_b
b_se = est_b.summary().tables[0]['std err'][0]
print(f"\n路径B系数提取: b = {b_coef:.4f}, se(b) = {b_se:.4f}")

正在拟合路径 A (T -> M)...
路径 A (T→M) 的平均效应: -17.1560

路径A详细结果:
                    Coefficient Results
===========================================================
    point_estimate stderr  zstat   pvalue ci_lower ci_upper
-----------------------------------------------------------
X0             0.0    0.0     2.37  0.018      0.0      0.0
X1             0.0    0.0    0.008  0.993   -0.001    0.001
X2           0.057  0.017    3.291  0.001    0.023    0.091
X3          -0.001  0.001    -1.25  0.211   -0.002      0.0
X4           0.002  0.002    0.712  0.476   -0.003    0.006
X5          -0.035  0.002  -20.145    0.0   -0.039   -0.032
X6           0.122  0.001  229.939    0.0    0.121    0.123
X7           -0.17  0.002  -90.094    0.0   -0.174   -0.166
X8           0.151  0.004   39.483    0.0    0.144    0.159
X9           -0.11  0.001 -112.698    0.0   -0.112   -0.108
X10          1.071  0.001 1161.773    0.0    1.069    1.073
X11         -0.449  0.002 -282.739    0.0   -0.452   -0.446
X12          0.031  0.008    3.873    0.0    0.016    0.047
X13         -0.007  0.025   -0.293   0.77   -0.056    0.041
                          CATE Intercept Results
=========================================================================
               point_estimate stderr    zstat    pvalue ci_lower ci_upper
-------------------------------------------------------------------------
cate_intercept        -17.156    0.0 -247601.705    0.0  -17.156  -17.156
-------------------------------------------------------------------------

<sub>A linear parametric conditional average treatment effect (CATE) model was fitted:
$Y = \Theta(X)\cdot T + g(X, W) + \epsilon$
where for every outcome $i$ and treatment $j$ the CATE $\Theta_{ij}(X)$ has the form:
$\Theta_{ij}(X) = X' coef_{ij} + cate\_intercept_{ij}$
Coefficient Results table portrays the $coef_{ij}$ parameter vector for each outcome $i$ and treatment $j$. Intercept Results table portrays the $cate\_intercept_{ij}$ parameter.</sub>
效应范围: [-5.7755, 5.3242]

正在拟合路径 B (M -> Y)...

KeyboardInterrupt:

In [39]:
est_a = LinearDML(
    model_y=RandomForestRegressor(n_estimators=70, random_state=42,min_samples_leaf=20,max_depth=5),
    model_t=RandomForestClassifier(n_estimators=70, random_state=42,min_samples_leaf=20,max_depth=5),  # T是二值变量
    discrete_treatment=True,  # 处理变量是离散的
    cv=5,
    random_state=42
)

# X: 控制变量，W: 年份固定效应
est_a.fit(Y=M, T=T, X=X, W=W)

# 获取政策对营商环境的平均处理效应
ate_a = est_a.intercept_
print(f"路径 A (T→M) 的平均效应: {ate_a:.4f}")

# 查看详细结果
print("\n路径A详细结果:")
print(est_a.summary())


# 如果有异质效应，可以看不同X下的效应
a_effects = est_a.effect(X)  # 个体处理效应
print(f"效应范围: [{a_effects.min():.4f}, {a_effects.max():.4f}]")

路径 A (T→M) 的平均效应: 1.5557

路径A详细结果:
                    Coefficient Results
============================================================
    point_estimate stderr   zstat   pvalue ci_lower ci_upper
------------------------------------------------------------
X0             0.0    0.0     6.214    0.0      0.0      0.0
X1             0.0  0.001     0.249  0.804   -0.001    0.001
X2           0.111  0.021     5.332    0.0     0.07    0.152
X3          -0.002  0.001    -1.916  0.055   -0.004      0.0
X4           0.004  0.004     1.025  0.305   -0.004    0.012
X5          -0.257  0.001  -463.284    0.0   -0.258   -0.256
X6          -0.459    0.0 -1415.055    0.0    -0.46   -0.459
X7          -0.997  0.001 -1407.975    0.0   -0.999   -0.996
X8           0.139  0.001   170.525    0.0    0.138    0.141
X9          -0.124    0.0  -391.022    0.0   -0.125   -0.124
X10          0.369  0.001   444.352    0.0    0.368    0.371
X11         -0.658    0.0 -1398.703    0.0   -0.659   -0.657
X12         -0.007  0.009    -0.772   0.44   -0.026    0.011
X13          0.046  0.001    72.375    0.0    0.044    0.047
                         CATE Intercept Results
=======================================================================
               point_estimate stderr   zstat   pvalue ci_lower ci_upper
-----------------------------------------------------------------------
cate_intercept          1.556    0.0 40666.033    0.0    1.556    1.556
-----------------------------------------------------------------------

<sub>A linear parametric conditional average treatment effect (CATE) model was fitted:
$Y = \Theta(X)\cdot T + g(X, W) + \epsilon$
where for every outcome $i$ and treatment $j$ the CATE $\Theta_{ij}(X)$ has the form:
$\Theta_{ij}(X) = X' coef_{ij} + cate\_intercept_{ij}$
Coefficient Results table portrays the $coef_{ij}$ parameter vector for each outcome $i$ and treatment $j$. Intercept Results table portrays the $cate\_intercept_{ij}$ parameter.</sub>
效应范围: [-12.3199, 15.0412]

In [ ]:
est_b = LinearDML(
    model_y=RandomForestRegressor(n_estimators=50, random_state=42),
    model_t=RandomForestRegressor(n_estimators=50, random_state=42),  # M是连续变量
    discrete_treatment=False,  # M是连续变量
    cv=5,
    random_state=42
)

# 注意：这里Y是因变量，M是处理变量
est_b.fit(Y=Y, T=M, X=X, W=W)  # X=None因为所有控制都放入了W

# 获取营商环境对诉求量的平均因果效应（直接效应）
ate_b = est_b.intercept_
print(f"路径 B 的平均效应: {ate_b:.4f}")

# 查看详细结果
print("\n路径B详细结果:")
print(est_b.summary())

路径 B 的平均效应: 0.1032

路径B详细结果:
Coefficient Results:  X is None, please call intercept_inference to learn the constant!
                       CATE Intercept Results
====================================================================
               point_estimate stderr zstat  pvalue ci_lower ci_upper
--------------------------------------------------------------------
cate_intercept          0.103  0.006 18.464    0.0    0.092    0.114
--------------------------------------------------------------------

<sub>A linear parametric conditional average treatment effect (CATE) model was fitted:
$Y = \Theta(X)\cdot T + g(X, W) + \epsilon$
where for every outcome $i$ and treatment $j$ the CATE $\Theta_{ij}(X)$ has the form:
$\Theta_{ij}(X) = X' coef_{ij} + cate\_intercept_{ij}$
Coefficient Results table portrays the $coef_{ij}$ parameter vector for each outcome $i$ and treatment $j$. Intercept Results table portrays the $cate\_intercept_{ij}$ parameter.</sub>

In [ ]:
est_c = LinearDML(
    model_y=RandomForestRegressor(n_estimators=200, random_state=123,max_depth=15),
    model_t=RandomForestClassifier(n_estimators=200, random_state=123,max_depth=15),
    discrete_treatment=True,
    cv=5,
    random_state=42
)

est_c.fit(Y=Y, T=T, X=X, W=W)

ate_c = est_c.intercept_
print(f"路径 C (T→Y) 的总效应: {ate_c:.4f}")

路径 C (T→Y) 的总效应: 3.3224

In [ ]:
est_cprime = LinearDML(
    model_y=RandomForestRegressor(n_estimators=70, random_state=42,
                                   min_samples_leaf=20, max_depth=5),
    model_t=RandomForestRegressor(n_estimators=70, random_state=42,
                                   min_samples_leaf=20, max_depth=5),  # 多变量处理用回归器
    discrete_treatment=False,  # 连续/多值处理变量设为 False
    cv=5,
    random_state=42
)

# 将 T 和 M 合并成二维数组作为处理变量
treatment = np.column_stack([T, M])

est_cprime.fit(Y=Y, T=treatment, X=X,W=W)
print("\n路径 c' 和 b (T+M → Y):")
print(est_cprime.summary())
c_prime = est_cprime.coef_[0]  # 直接效应 c'
b = est_cprime.coef_[1]       # M → Y 的效应 b

In [66]:
est_c.summary()

<class 'econml.utilities.Summary'>
"""
                    Coefficient Results
===========================================================
    point_estimate stderr  zstat   pvalue ci_lower ci_upper
-----------------------------------------------------------
X0             0.0    0.0    0.734  0.463     -0.0      0.0
X1            -0.0    0.0   -1.301  0.193   -0.001      0.0
X2           0.009  0.007    1.342   0.18   -0.004    0.023
X3            -0.0    0.0   -0.995   0.32   -0.001      0.0
X4           0.001  0.001    1.771  0.076     -0.0    0.002
X5           0.014  0.002    8.614    0.0     0.01    0.017
X6          -0.175    0.0 -688.156    0.0   -0.175   -0.174
X7            0.04  0.002   21.918    0.0    0.036    0.044
X8          -0.032  0.004   -8.395    0.0    -0.04   -0.025
X9           -0.06  0.001   -73.02    0.0   -0.062   -0.059
X10          0.043  0.001   73.053    0.0    0.042    0.044
X11          0.058  0.002   36.139    0.0    0.055    0.061
X12         -0.019  0.003   -6.429    0.0   -0.025   -0.013
X13         -0.005  0.024   -0.227   0.82   -0.052    0.041
                         CATE Intercept Results
=======================================================================
               point_estimate stderr   zstat   pvalue ci_lower ci_upper
-----------------------------------------------------------------------
cate_intercept          3.322    0.0 49446.886    0.0    3.322    3.323
-----------------------------------------------------------------------

<sub>A linear parametric conditional average treatment effect (CATE) model was fitted:
$Y = \Theta(X)\cdot T + g(X, W) + \epsilon$
where for every outcome $i$ and treatment $j$ the CATE $\Theta_{ij}(X)$ has the form:
$\Theta_{ij}(X) = X' coef_{ij} + cate\_intercept_{ij}$
Coefficient Results table portrays the $coef_{ij}$ parameter vector for each outcome $i$ and treatment $j$. Intercept Results table portrays the $cate\_intercept_{ij}$ parameter.</sub>
"""

In [45]:
# 间接效应（中介效应）= 路径A × 路径B
indirect_effect = ate_a * ate_b
print(f"间接效应 (T→M→Y): {indirect_effect:.4f}")

# 直接效应（T对Y的直接效应）= 总效应 - 间接效应
direct_effect = ate_c - indirect_effect
print(f"直接效应 (T→Y 除去M的中介): {direct_effect:.4f}")

间接效应 (T→M→Y): -1.3987
直接效应 (T→Y 除去M的中介): 4.4920

In [14]:
# 1. 提取路径 A 的核心系数 (gamma_1: T -> M)
summary_a = est_a.summary().tables[0]
# 在 LinearDML 中，intercept_ 对应的就是处理变量 T 的平均系数
gamma_1_val = est_a.intercept_ 
p_val_a = float(summary_a.data[1][4]) # 提取 P 值

# 2. 提取路径 B 的核心系数 (beta_2: M -> Y)
summary_b = est_b.summary().tables[0]
beta_2_val = est_b.intercept_
p_val_b = float(summary_b.data[1][4])

print(f"--- 中介效应核心指标回顾 ---")
print(f"路径 A (T -> M): 系数 = {gamma_1_val:.4f}, P值 = {p_val_a:.4f}")
print(f"路径 B (M -> Y): 系数 = {beta_2_val:.4f}, P值 = {p_val_b:.4f}")

# 3. 判断中介成立条件
if p_val_a < 0.05 and p_val_b < 0.05:
    mediation_effect = gamma_1_val * beta_2_val
    print(f"结论：中介效应显著！间接效应大小为: {mediation_effect:.4f}")
else:
    print("结论：中介效应不显著，请检查数据质量或理论逻辑。")

Coefficient Results:  'LinearDML' object has no attribute '_inference'
CATE Intercept Results:  'LinearDML' object has no attribute '_inference'

AttributeError: 'NoneType' object has no attribute 'tables'